
services:

    db:
     image: postgres:alpine
     container_name: db
     restart: always
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: resizely
     ports:
       - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data
    
    app: 
     build:
      context: ../
      dockerfile: docker/Dockerfile.dev
      args:
       - DATABASE_URL=postgresql://postgres:postgres@db:5432/resizely
     container_name: resizly-app
     ports:
       - "3000:3000"
     environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/resizely

     depends_on:
      - db     
     volumes:
       - ../:/app
       - /app/node_modules

volumes:
  postgres_data: